import { ThreeDMarquee } from "@/components/ui/ThreeDMarquee";

export default function Associated() {
  const images = [
    "/aapc.png",
    "/asrm.png",
    "/bbb.png",
    "/hippa.png",
    "/iso.png",
    "/aapc.png",
    "/asrm.png",
    "/bbb.png",
    "/hippa.png",
    "/iso.png",
    "/aapc.png",
    "/asrm.png",
    "/bbb.png",
    "/hippa.png",
    "/iso.png",
    "/aapc.png",
    "/asrm.png",
    "/bbb.png",
    "/hippa.png",
    "/iso.png",
    "/aapc.png",
    "/asrm.png",
    "/bbb.png",
    "/hippa.png",
    "/iso.png",
    "/aapc.png",
    "/asrm.png",
    "/bbb.png",
    "/hippa.png",
    "/iso.png",
    "/aapc.png",
    "/asrm.png",
    "/bbb.png",
    "/hippa.png",
    "/iso.png",
    "/aapc.png",
    "/asrm.png",
    "/bbb.png",
    "/hippa.png",
    "/iso.png",
    "/aapc.png",
    "/asrm.png",
    "/bbb.png",
    "/hippa.png",
    "/iso.png",

    // "https://assets.aceternity.com/cloudinary_bkp/3d-card.png",
    // "https://assets.aceternity.com/animated-modal.png",
    // "https://assets.aceternity.com/animated-testimonials.webp",
    // "https://assets.aceternity.com/cloudinary_bkp/Tooltip_luwy44.png",
    // "https://assets.aceternity.com/github-globe.png",
    // "https://assets.aceternity.com/glare-card.png",
    // "https://assets.aceternity.com/layout-grid.png",
    // "https://assets.aceternity.com/flip-text.png",
    // "https://assets.aceternity.com/hero-highlight.png",
    // "https://assets.aceternity.com/carousel.webp",
    // "https://assets.aceternity.com/placeholders-and-vanish-input.png",
    // "https://assets.aceternity.com/shooting-stars-and-stars-background.png",
    // "https://assets.aceternity.com/signup-form.png",
    // "https://assets.aceternity.com/cloudinary_bkp/stars_sxle3d.png",
    // "https://assets.aceternity.com/spotlight-new.webp",
    // "https://assets.aceternity.com/cloudinary_bkp/Spotlight_ar5jpr.png",
    // "https://assets.aceternity.com/cloudinary_bkp/Parallax_Scroll_pzlatw_anfkh7.png",
    // "https://assets.aceternity.com/tabs.png",
    // "https://assets.aceternity.com/cloudinary_bkp/Tracing_Beam_npujte.png",
    // "https://assets.aceternity.com/cloudinary_bkp/typewriter-effect.png",
    // "https://assets.aceternity.com/glowing-effect.webp",
    // "https://assets.aceternity.com/hover-border-gradient.png",
    // "https://assets.aceternity.com/cloudinary_bkp/Infinite_Moving_Cards_evhzur.png",
    // "https://assets.aceternity.com/cloudinary_bkp/Lamp_hlq3ln.png",
    // "https://assets.aceternity.com/macbook-scroll.png",
    // "https://assets.aceternity.com/cloudinary_bkp/Meteors_fye3ys.png",
    // "https://assets.aceternity.com/cloudinary_bkp/Moving_Border_yn78lv.png",
    // "https://assets.aceternity.com/multi-step-loader.png",
    // "https://assets.aceternity.com/vortex.png",
    // "https://assets.aceternity.com/wobble-card.png",
  ];

  return (
    <section className="py-20">
      <div className="text-xl md:text-5xl text-primary-blue font-bold text-center p-4 mb-6">
        <h2>In Associated with</h2>
      </div>
      <ThreeDMarquee images={images} className="max-w-7xl mx-auto" />
    </section>
  );
}
